### ISSUE TITLE
1991번: 트리 순회

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/Classroom4_Week02_Team7_StudyNotes#2]
https://www.acmicpc.net/problem/1991

관련 단원: 9-1

**Comment by kugorang** [comment]
그러면 삼중 트리일 때도 중위 순회가 되나요?

**Comment by GEUMDOHYEON** [comment]
삼진 트리나 그 이상의 다진 트리도 중위순회, 전위 순회, 후위 순회 등과 유사한 방법으로 가질 수 있습니다. 다만, 트리의 구조가 복잡해지면서 순회 방법이 그에 따라 변할 수 있다고 합니다. 삼진트리 전위 순회 순서는 현재 노드, 왼쪽자식, 중간자식, 오른쪽 자식 순으로 중위 순회는 왼쪽자식, 현재노드, 중간자식, 오른쪽자식 순으로 후위 순회는 왼쪽자식, 중간자식, 오른쪽자식, 현재 노드 순으로 간다고 알고 있습니다!
